#!/bin/bash
#
# Hemera - Intelligent System (https://sourceforge.net/projects/hemerais)
# Copyright (C) 2010-2011 Bertrand Benoit <projettwk@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see http://www.gnu.org/licenses
# or write to the Free Software Foundation,Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301  USA
#
# Version: 1.0
# Description: uses espeak to perfom text to speech.
#
# must NOT be directly called.

[ "$moduleMode" != "espeak" ] && exit $ERROR_MODE

## Configuration check.
checkAndSetConfig "$CONFIG_KEY.tool.path" "$CONFIG_TYPE_BIN"
espeakBin="$h_lastConfig"
checkAndSetConfig "$CONFIG_KEY.tool.options" "$CONFIG_TYPE_OPTION"
espeakOptions="$h_lastConfig"

# Usage: speechSentence <sentence> [<additional options>]
function speechSentence() {
  # Modus operandi:
  #  - uses espeak to generate speech sound
  #  - uses finally the speech sound player
  info "System will play speech '$1', using only espeak"
  "$espeakBin" -v "$language" $espeakOptions $2 "$1" |"$soundPlayerBin" $soundPlayerOptions
}

# Usage: speechFileContents <file path>
function speechFileContents() {
  speechSentence "$1" "-m -f"
}
