#!/bin/bash
#
# Hemera - Intelligent System (https://sourceforge.net/projects/hemerais)
# Copyright (C) 2010-2011 Bertrand Benoit <projettwk@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see http://www.gnu.org/licenses
# or write to the Free Software Foundation,Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301  USA
#
# Version: 1.0
# Description: say command.
# Keyword: SAY_CMD
#
# This script must NOT be directly called.

# Ensures there is at least one argument.
if [ $wordsCount -lt 2 ]; then
  speechToSay "$SAY_CMD_BAD_USE_I18N" "$_inputPath"
  notifyErrInput
else
  whatToSay=$( extractRecognitionResultArgument "$_inputPath" )
  writeMessage "$inputString: SAY command detected -> preparing what to say: $whatToSay"
  speechToSay "$whatToSay" "$_inputPath" && notifyDoneInput || notifyErrInput
fi
